### ISSUE TITLE
코드 품질을 위한 도구 논의

### ISSUE THREAD

**Issue by castedice** [nullstack-developer/python_clean_code#1]
## 책에서 소개한 도구
- 코드 포매터: black
- 정적 타입 검사기: mypy
- 정적 검사기: pylint
- 테스트 도구: pytest

## 추가적으로 고려해볼 도구
- 정적 검사기: wemakepython
  - flake8의 확장버전
- monkeytype
  - mypy와 세트로 많이 사용하는 것으로 보임

## Awesome-python에서 소개하고 있는 도구
[https://github.com/vinta/awesome-python#code-analysis](https://github.com/vinta/awesome-python#code-analysis)

**Comment by jangsc0000** [comment]
## Black
### Black Install

```
$ pip install black
```

### Black Usage


```
$ black main.py
reformatted main.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

**Comment by castedice** [comment]
black은 지금도 잘 쓰고 있고 굉장히 좋은 도구라고 생각이 되는데,
wemake-python과 충돌이 있음 [링크](https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/auto-formatters.html)
물론 충돌나는 부분은 wemake-python에서 꺼주는 방법으로 해결할 수는 있지만, 위의 링크에서 이야기하는 내용도 고려해볼 필요가 있을 것 같음

**Comment by jangsc0000** [comment]
> black은 지금도 잘 쓰고 있고 굉장히 좋은 도구라고 생각이 되는데, wemake-python과 충돌이 있음 [링크](https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/auto-formatters.html) 물론 충돌나는 부분은 wemake-python에서 꺼주는 방법으로 해결할 수는 있지만, 위의 링크에서 이야기하는 내용도 고려해볼 필요가 있을 것 같음

**Comment by castedice** [comment]
추려본 도구 목록
formatter: black + isort
linter: wemake-python-styleguide
type checker: mypy + monkeytype
test: pytest

**Comment by jangsc0000** [comment]
> 추려본 도구 목록
> formatter: black + isort
> linter: wemake-python-styleguide
> type checker: mypy + monkeytype
> test: pytest

각 툴들에 대해서 간단하게 사용법 정리하고,
한꺼번에 세팅하는 설정파일이나 스크립트 만들면 좋을 것 같아요

**Comment by castedice** [comment]
초안 코드 업로드 했습니다. 피드백 주세요
작성하면서 느낀게
poetry를 사용할 것인지 여부
그리고 github ci cd를 위한 작업도 같이 작성하는게 좋아보여요.

**Comment by jangsc0000** [comment]
## isort
isort is a Python utility / library to sort imports alphabetically, and automatically separated into sections and by type.
### isort Install
```
pip install isort
```
### isort Usage

#### CLI
```
isort . --profile black
isort project1
isort setup.py
```
#### Github Action
```
name: Run isort
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements-test.txt"
```
#### pre-commit
```
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
```
